# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mars_robot_msgs/motor_data_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motor_data_msg(genpy.Message):
  _md5sum = "1a39659befe0182ae29a42de47aa67fc"
  _type = "mars_robot_msgs/motor_data_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 auger_current
float32 auger_speed
float32 right_loco_current
float32 left_loco_current"""
  __slots__ = ['auger_current','auger_speed','right_loco_current','left_loco_current']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       auger_current,auger_speed,right_loco_current,left_loco_current

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motor_data_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.auger_current is None:
        self.auger_current = 0.
      if self.auger_speed is None:
        self.auger_speed = 0.
      if self.right_loco_current is None:
        self.right_loco_current = 0.
      if self.left_loco_current is None:
        self.left_loco_current = 0.
    else:
      self.auger_current = 0.
      self.auger_speed = 0.
      self.right_loco_current = 0.
      self.left_loco_current = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.auger_current, _x.auger_speed, _x.right_loco_current, _x.left_loco_current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.auger_current, _x.auger_speed, _x.right_loco_current, _x.left_loco_current,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.auger_current, _x.auger_speed, _x.right_loco_current, _x.left_loco_current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.auger_current, _x.auger_speed, _x.right_loco_current, _x.left_loco_current,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
